# Name of this app
service: fizzy
image: fizzy


#-- About your deployment --#

# Where to deploy fizzy
servers:
  web:
    - 5.161.75.133

# How you connect to your server
ssh:
  user: deploy

# Automatic SSL
proxy:
  ssl: true
  host: fizzy.evansparkman.dev

# Your application configuration (secrets come from .kamal/secrets).
env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
  clear:
    BASE_URL: https://fizzy.evansparkman.dev
    MAILER_FROM_ADDRESS: noreply@evansparkman.dev
    SMTP_ADDRESS: smtp.resend.com
    SMTP_PORT: "587"
    SMTP_DOMAIN: evansparkman.dev
    SMTP_AUTHENTICATION: plain
    MULTI_TENANT: "false"
    SOLID_QUEUE_IN_PUMA: "true"


#-- General configuration --#

# Use a local registry to deploy
registry:
  server: 5.161.75.133:5000
  username: deploy
  password:
    - KAMAL_REGISTRY_PASSWORD

# Handy aliases for interacting with your deployment. For eaxmple: `bin/kamal console` will connect to a
# Rails console in production.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "fizzy_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
